### ISSUE TITLE
W ustawieniach pokoju można ustawić ujemny czas

### ISSUE THREAD

**Issue by sokolowskam** [kichel98/BlankietyGalantow#109]
kiedy się ustawi czas na ujemny, aplikacja oczywiście się wywala.

**Comment by KyrietS** [comment]
Walidacji niczego nie ma prawie wcale na backu 😄

**Comment by sokolowskam** [comment]
ja tylko piszę, co znalazłam :| a poza tym nie trzeba tego walidować na backu, wystarczy na froncie dodać w tagu <input>  zakres.

**Comment by sokolowskam** [comment]
zmergowane
