### ISSUE TITLE
Moduł "Talia kart"

### ISSUE THREAD

**Issue by KyrietS** [kichel98/BlankietyGalantow#11]
# Talia kart
Potrzeba jest klasa reprezentująca talię kart używaną w grze. Dane powinny być wczytywane z pliku tekstowego o jakimś formacie (JSON? Zwykły tekst? CSV?)
Funkcjonalności talii:
* Wczytywanie danych z pliku
* Tasowanie
* Wydawanie karty (+ wyrzucanie jej z talii)
* Sprawdzanie ile kart pozostało w talii

# Karta
Wraz z samą talią potrzebna jest też klasa reprezentująca pojedynczą kartę. Każda karta musi mieć unikalny w całej talii *id*, aby dało się je łatwo rozróżnić.
Cechy karty:
* id (może być nadawany przy wczytywaniu, nie musi być w pliku)
* treść
* kolor (biały, czarny?)*

\* tutaj może lepiej jest zrobić osobną klasę dla białej i czarnej karty, bo one są w tej grze czymś zupełnie różnym i prawdopodobnie będą wczytywane z różnych plików. Może być np. talia kart Card, a klasami pochodnymi od Card będzie WhiteCard i BlackCard. Wtedy możemy zrobić dwie talie różnych kart (polimorfizm)

Wraz z tym taskiem idzie potrzeba przygotowania jakichś mock'owych danych. Tymczasowo mogą to być dane w stylu:
```
- treść białej karty 1
- treść białej karty 2
...
```
Ważne, aby było ich dużo. Z małej talii nie da się przeprowadzić rozgrywki, a dobieranie już wylosowanych kart to zawsze jest złych pomysł przypadku tej gry.

**Comment by ketrab321** [comment]
Na jakim etapie jest praca nad tym modułem?

**Comment by jkt44** [comment]
> Na jakim etapie jest praca nad tym modułem?

Kombinuję jeszcze nad sensowną implementacją zanim wrzucę commity. Dzisiaj w nocy powinna wlecieć jakaś działająca wersja którą się usprawni i zrobi pull request jutro.
