### ISSUE TITLE
Gracz zostaje Mistrzem Kart

### ISSUE THREAD

**Issue by KyrietS** [kichel98/BlankietyGalantow#49]
Klasa `GameMaster` przechowuje pole `card_master` (patrz: klasa `Room` trzymająca `admin`). Zasady przydzielania Mistrza Kart:
* Jeśli pokój jest pusty, Mistrzem Kart zostaje pierwszy gracz, który wejdzie.
* Jeśli obecny Mistrz Kart opuści pokój, to Mistrzem Kart zostaje losowa osoba z pokoju (lub osoba "następna", ale to może być trudne do ładnego zaimplementowania, bo po opuszczeniu pokoju przez gracza nie ma go już na liście i nie wiadomo kto miał być za nim).
* Jeśli runda się zakończy, Mistrzem Kart zostaje **kolejna** osoba według kolejności na liście `self.players`.

## Uwaga
Zmienna `card_master` nie ma trzymać indeksu w tablicy, ani `id`. Indeksy się mogą zmieniać! Można trzymać po prostu referencję do całego obiektu `Player`a. Ułatwi to sprawdzanie i porównywanie.

Aby wziąć kolejnego gracza można użyć `(players.index(card_master) + 1) % len(players)`. Oczywiście trzeba to wyrażenie zapisać do jakiejś ładnie nazwanej zmiennej i wtedy jej użyć `next_player_in_round = ...`

## Działanie
Po zrobieniu tego taska powinien być możliwy do odtworzenia następujący scenariusz:
* gracz A zakłada serwer (`card_master` = None)
* gracz A wchodzi na serwer i zostaje Mistrzem Kart (`card_master` = A)
* gracz A wychodzi z serwera (`card_master` = None)
* gracz B wchodzi na serwer i zostaje Mistrzem Kart
* gracz C wchodzi na serwer
* gracz D wchodzi na serwer
* gracz B wychodzi z serwera. Ktoś inny na serwerze zostaje automatycznie Mistrzem Kart.

**Comment by ketrab321** [comment]
Co do tego scenariusza trzeba pamiętać, że w przyszłości będziemy usuwali puste pokoje, więc ustawianie card_master na None gdy pokój jest pusty jest niepotrzebne 😉

**Comment by KyrietS** [comment]
> Co do tego scenariusza trzeba pamiętać, że w przyszłości będziemy usuwali puste pokoje, więc ustawianie card_master na None gdy pokój jest pusty jest niepotrzebne 😉

Good point, zapomniałem o tym. Dodam taska z tym.

Warto zaznaczyć, że to **wyjście** ostatniego gracza powoduje usunięcie pokoju. Serwer bez graczy jak najbardziej może istnieć 😃
