### ISSUE TITLE
RealTime lista pokoi

### ISSUE THREAD

**Issue by ketrab321** [kichel98/BlankietyGalantow#51]
Przydałoby się zrobić interwałowe odpytywanie api o listę pokoi, aby uzyskać aktualizującą się na bieżąco listę serwerów.

**Comment by KyrietS** [comment]
Może być przycisk "odśwież" albo tak jak mówisz auto-refresh. Ja tak wymyśliłem wcześniej to REST API na próbę, aby była różnorodność :stuck_out_tongue: i prostota implementacji. 

Nic nie stoi na przeszkodzie, aby to przerobić to na WebSockety i aktualizować serwery na żywo. Ale to trochę skomplikuje backend i zużyje dużo zasobów. Auto-refresh powinien być git na razie :+1:

**Comment by kichel98** [comment]
Przy okazji, jak zostanie to zrobione, to można dorobić blokowanie wejścia do pełnego/zamkniętego pokoju. Teraz, pomimo tego, że ładnie widać na froncie, że pokój jest pełny/zamknięty, to i tak można spróbować do niego wejść. Wtedy backend odpowiada komunikatem o błędzie - teraz ma to nawet sens, bo dane o stanie pokojów nie są aktualizowane. Gdy już będą zawsze aktualne, to warto ograniczyć liczbę zapytań i zablokować możliwość próby wejścia z frontu (oczywiście nie usuwamy kodu z backendu, bo nikomu nie można ufać w tych czasach 😉)

**Comment by KyrietS** [comment]
Specjalnie zostawiliśmy możliwość "próby" wejścia do pełnego i zamkniętego pokoju na froncie. Zrobiliśmy taki ładny Error Screen, że szkoda by było gdyby nikt nie zobaczył jaki jest śliczny 😄

**Comment by kichel98** [comment]
To może znajdźmy jakieś inne miejsce, w którym można go pokazać, bo to słaby argument na rzucanie błędu, który można po prostu wcześniej zablokować XD Poza tym, jeśli aktualizowanie nie będzie co 1s, to można tak czy siak doprowadzić do niego

**Comment by KyrietS** [comment]
Jeeju luz, to jest dla "fanu" zostawione przecież xD
Zablokowanie wejścia, to kwestia 5 minut. Możesz dodać taska, aby nie zapomnieć 😛
