### ISSUE TITLE
Zmiana kolejności stosików PLAYED_CARDS

### ISSUE THREAD

**Issue by KyrietS** [kichel98/BlankietyGalantow#81]
Obecnie jak serwer wysyła graczom PLAYED_CARDS, to wysyła je w takiej kolejności, w jakiej są pokazywani gracze.

Jeśli gracze są w takiej kolejności:
![image](https://user-images.githubusercontent.com/19170699/82840122-ca715580-9ed1-11ea-8d63-7cb0660c3707.png)

To wiadomo, że pierwszy stosik zawsze należy do gracza **Typosz** a drugi do **Henio**
![image](https://user-images.githubusercontent.com/19170699/82840255-3358cd80-9ed2-11ea-9254-a4354cf4f52a.png)

Trzeba przed wysłaniem tych stosików je jakoś wymieszać na serwerze.

**Comment by sokolowskam** [comment]
issue do zamknięcia - zrobione w ramach PR #90
