### ISSUE TITLE
Odkrywanie kart "na żywo" u wszystkich graczy

### ISSUE THREAD

**Issue by KyrietS** [kichel98/BlankietyGalantow#82]
Kiedy Mistrz Kart odkrywa karty u siebie, to powinien wysyłać do serwera komunikat o tym, że właśnie odkrył konkretny stosik z kartami. Może np. wysyłać indeks w tablicy (każdy powinien mieć taką samą kolejność). Wtedy pokój rozsyła zaktualizowane karty wszystkim graczom, gdzie jeden ze stosików został wzbogacony o opcję `revealed: true`.

Dzięki temu wszyscy na żywo widzą jak Mistrz Kart odsłania karty. Serwer może wysyłać **cały** zestaw kart. Nie trzeba się bawić w wysyłanie pojedynczego stosika albo id itd. Zwyczajnie na backendzie jeden ze stosików ustawiamy na `revealed: True` i odpalamy `send_played_cards_to_all` czy jakoś tak. Frontend jest gotowy i nic nie trzeba w nim zmieniać (chyba)  :-)

**Comment by sokolowskam** [comment]
czy jest jakaś zmienna, która sensownie łączy ze sobą id zagranego stosiku i gracza, który go dołożył? Szukałam czegoś, co dałoby radę, ale nie znalazłam. Obecnie funkcjonalność prawie działa, problemem jest natomiast właśnie ten brak mapowania między stosikami w fazie wyboru, a graczami.

**Comment by sokolowskam** [comment]
w efekcie powiązałam id stosiku z indeksem danego gracza w liście `players` klasy `GameMaster` przy czym wiem, że może to być zły pomysł, ale lepszego nie znalazłam.
