### ISSUE TITLE
Tekst wychodzi poza kartę

### ISSUE THREAD

**Issue by KyrietS** [kichel98/BlankietyGalantow#93]
Brakuje `overflow-wrap` albo czegoś podobnego.

![image](https://user-images.githubusercontent.com/19170699/83258176-182ddc80-a1b6-11ea-81e7-8ef329f655de.png)

**Comment by sokolowskam** [comment]
oprócz tego zdarzają się również karty, na których treść się nie mieści, bo jest za długa, np tutaj: 
![Screenshot from 2020-06-01 11-29-01](https://user-images.githubusercontent.com/38133466/83396116-c24a7600-a3fb-11ea-8006-8d923d2fbab7.png)
