### ISSUE TITLE
Task exception was never retrieved (timer)

### ISSUE THREAD

**Issue by KyrietS** [kichel98/BlankietyGalantow#96]
```
ERROR:    Task exception was never retrieved
future: <Task finished coro=<Timer._job() done, defined at ./blankiety_galantow/core/utils/timer.py:10> exception=CancelledError()>
concurrent.futures._base.CancelledError
```
Błąd nie crashuje aplikacji, ale pojawia się w logach serwera. Gdzieś nie łapiemy wyjątku.

**Comment by sokolowskam** [comment]
@ketrab321 bug pojawia się, kiedy kończy się odliczany czas i game master sam dokłada kartę za użytkownika/wybiera katrę zamiast mistrza kart.

**Comment by ketrab321** [comment]
Chyba wiem w czym jest problem. Problem powoduje to, że kick rzuca wyjątkiem, a jest wywoływany w asynchronicznych callbacku w timerze. Wydaje mi się, że tego dotyczy ten błąd, że przez to, że timer działa asynchronicznie, to wyjątki działają trochę inaczej.

**Comment by ketrab321** [comment]
Trzeba by było sprawdzić, czy wyrzucenie wyjątku z kicka naprawi ten błąd.

**Comment by sokolowskam** [comment]
nie do końca, bo kick nie jest jeszcze wtedy wywoływany.

**Comment by sokolowskam** [comment]
co więcej, w obecnej formie `KickException` nie jest nigdzie rzucany.

**Comment by KyrietS** [comment]
Tak i jest to przyczyna buga #87

**Comment by sokolowskam** [comment]
wiem, najwyraźniej wywołanie `await self.socket.close()` coś blokuje.
